language: ruby
cache:
  directories:
  - vendor/bundle
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.3.0
  - ruby-head
  - jruby
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-2

addons:
  apt:
    packages:
    - libevent-dev
    - libxml2-dev
    - libcurl4-gnutls-dev
    - python2.7-dev
    - python-virtualenv


install: bundle install --deployment --jobs=3 --retry=3

script:
    # creating and activating virtualenv
    - virtualenv -p python2.7 --distribute rubythumbor
    - source ./rubythumbor/bin/activate

    # install python requirements
    - pip install -r test_requirements.txt --use-mirrors

    # verify both requirements were met
    - INSTALLDIR=$(python -c "import os; import thumbor; print(os.path.dirname(thumbor.__file__))")

    # finally run tests
    - bundle exec rake spec
after_success:
  coveralls
